### ISSUE TITLE
Make a tag/release for PyHEP 2022 "proceedings"

### ISSUE THREAD

**Issue by eduardo-rodrigues** [HDembinski/PyHEP-2022-iminuit#1]
Hello @HDembinski, can you kindly prepare the tag/release so that I then use it to mint a DOI on Zenodo and attach it to the workshop "proceedings" https://zenodo.org/communities/pyhep2022? Advance thanks.

**Comment by HDembinski** [comment]
I generated tag and release v1.0. Thank you!
